/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthletesIndexRouteImport } from './routes/athletes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AthletesSlugRouteImport } from './routes/athletes/$slug'
import { Route as DashboardSponsorIndexRouteImport } from './routes/dashboard/sponsor/index'
import { Route as DashboardAthleteIndexRouteImport } from './routes/dashboard/athlete/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardSponsorDiscoverRouteImport } from './routes/dashboard/sponsor/discover'
import { Route as DashboardSponsorAthletesRouteImport } from './routes/dashboard/sponsor/athletes'
import { Route as DashboardAthleteResultsRouteImport } from './routes/dashboard/athlete/results'
import { Route as DashboardAthleteReachRouteImport } from './routes/dashboard/athlete/reach'
import { Route as DashboardAthleteProfileRouteImport } from './routes/dashboard/athlete/profile'
import { Route as DashboardAthleteConnectionsRouteImport } from './routes/dashboard/athlete/connections'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesIndexRoute = AthletesIndexRouteImport.update({
  id: '/athletes/',
  path: '/athletes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesSlugRoute = AthletesSlugRouteImport.update({
  id: '/athletes/$slug',
  path: '/athletes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSponsorIndexRoute = DashboardSponsorIndexRouteImport.update({
  id: '/dashboard/sponsor/',
  path: '/dashboard/sponsor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAthleteIndexRoute = DashboardAthleteIndexRouteImport.update({
  id: '/dashboard/athlete/',
  path: '/dashboard/athlete/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/dashboard/admin/',
  path: '/dashboard/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSponsorDiscoverRoute =
  DashboardSponsorDiscoverRouteImport.update({
    id: '/dashboard/sponsor/discover',
    path: '/dashboard/sponsor/discover',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSponsorAthletesRoute =
  DashboardSponsorAthletesRouteImport.update({
    id: '/dashboard/sponsor/athletes',
    path: '/dashboard/sponsor/athletes',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAthleteResultsRoute = DashboardAthleteResultsRouteImport.update({
  id: '/dashboard/athlete/results',
  path: '/dashboard/athlete/results',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAthleteReachRoute = DashboardAthleteReachRouteImport.update({
  id: '/dashboard/athlete/reach',
  path: '/dashboard/athlete/reach',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAthleteProfileRoute = DashboardAthleteProfileRouteImport.update({
  id: '/dashboard/athlete/profile',
  path: '/dashboard/athlete/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAthleteConnectionsRoute =
  DashboardAthleteConnectionsRouteImport.update({
    id: '/dashboard/athlete/connections',
    path: '/dashboard/athlete/connections',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/athletes/': typeof AthletesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/athlete/profile': typeof DashboardAthleteProfileRoute
  '/dashboard/athlete/reach': typeof DashboardAthleteReachRoute
  '/dashboard/athlete/results': typeof DashboardAthleteResultsRoute
  '/dashboard/athlete/connections': typeof DashboardAthleteConnectionsRoute
  '/dashboard/sponsor/athletes': typeof DashboardSponsorAthletesRoute
  '/dashboard/sponsor/discover': typeof DashboardSponsorDiscoverRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/athlete/': typeof DashboardAthleteIndexRoute
  '/dashboard/sponsor/': typeof DashboardSponsorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/athletes': typeof AthletesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/athlete/profile': typeof DashboardAthleteProfileRoute
  '/dashboard/athlete/reach': typeof DashboardAthleteReachRoute
  '/dashboard/athlete/results': typeof DashboardAthleteResultsRoute
  '/dashboard/athlete/connections': typeof DashboardAthleteConnectionsRoute
  '/dashboard/sponsor/athletes': typeof DashboardSponsorAthletesRoute
  '/dashboard/sponsor/discover': typeof DashboardSponsorDiscoverRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/athlete': typeof DashboardAthleteIndexRoute
  '/dashboard/sponsor': typeof DashboardSponsorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/athletes/': typeof AthletesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/athlete/profile': typeof DashboardAthleteProfileRoute
  '/dashboard/athlete/reach': typeof DashboardAthleteReachRoute
  '/dashboard/athlete/results': typeof DashboardAthleteResultsRoute
  '/dashboard/athlete/connections': typeof DashboardAthleteConnectionsRoute
  '/dashboard/sponsor/athletes': typeof DashboardSponsorAthletesRoute
  '/dashboard/sponsor/discover': typeof DashboardSponsorDiscoverRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/athlete/': typeof DashboardAthleteIndexRoute
  '/dashboard/sponsor/': typeof DashboardSponsorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/athletes/$slug'
    | '/auth/login'
    | '/auth/register'
    | '/athletes/'
    | '/api/auth/$'
    | '/dashboard/athlete/profile'
    | '/dashboard/athlete/reach'
    | '/dashboard/athlete/results'
    | '/dashboard/athlete/connections'
    | '/dashboard/sponsor/athletes'
    | '/dashboard/sponsor/discover'
    | '/dashboard/admin/'
    | '/dashboard/athlete/'
    | '/dashboard/sponsor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/athletes/$slug'
    | '/auth/login'
    | '/auth/register'
    | '/athletes'
    | '/api/auth/$'
    | '/dashboard/athlete/profile'
    | '/dashboard/athlete/reach'
    | '/dashboard/athlete/results'
    | '/dashboard/athlete/connections'
    | '/dashboard/sponsor/athletes'
    | '/dashboard/sponsor/discover'
    | '/dashboard/admin'
    | '/dashboard/athlete'
    | '/dashboard/sponsor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/athletes/$slug'
    | '/auth/login'
    | '/auth/register'
    | '/athletes/'
    | '/api/auth/$'
    | '/dashboard/athlete/profile'
    | '/dashboard/athlete/reach'
    | '/dashboard/athlete/results'
    | '/dashboard/athlete/connections'
    | '/dashboard/sponsor/athletes'
    | '/dashboard/sponsor/discover'
    | '/dashboard/admin/'
    | '/dashboard/athlete/'
    | '/dashboard/sponsor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AthletesSlugRoute: typeof AthletesSlugRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AthletesIndexRoute: typeof AthletesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DashboardAthleteProfileRoute: typeof DashboardAthleteProfileRoute
  DashboardAthleteReachRoute: typeof DashboardAthleteReachRoute
  DashboardAthleteResultsRoute: typeof DashboardAthleteResultsRoute
  DashboardAthleteConnectionsRoute: typeof DashboardAthleteConnectionsRoute
  DashboardSponsorAthletesRoute: typeof DashboardSponsorAthletesRoute
  DashboardSponsorDiscoverRoute: typeof DashboardSponsorDiscoverRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAthleteIndexRoute: typeof DashboardAthleteIndexRoute
  DashboardSponsorIndexRoute: typeof DashboardSponsorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/': {
      id: '/athletes/'
      path: '/athletes'
      fullPath: '/athletes/'
      preLoaderRoute: typeof AthletesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$slug': {
      id: '/athletes/$slug'
      path: '/athletes/$slug'
      fullPath: '/athletes/$slug'
      preLoaderRoute: typeof AthletesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sponsor/': {
      id: '/dashboard/sponsor/'
      path: '/dashboard/sponsor'
      fullPath: '/dashboard/sponsor/'
      preLoaderRoute: typeof DashboardSponsorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/athlete/': {
      id: '/dashboard/athlete/'
      path: '/dashboard/athlete'
      fullPath: '/dashboard/athlete/'
      preLoaderRoute: typeof DashboardAthleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sponsor/discover': {
      id: '/dashboard/sponsor/discover'
      path: '/dashboard/sponsor/discover'
      fullPath: '/dashboard/sponsor/discover'
      preLoaderRoute: typeof DashboardSponsorDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sponsor/athletes': {
      id: '/dashboard/sponsor/athletes'
      path: '/dashboard/sponsor/athletes'
      fullPath: '/dashboard/sponsor/athletes'
      preLoaderRoute: typeof DashboardSponsorAthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/athlete/results': {
      id: '/dashboard/athlete/results'
      path: '/dashboard/athlete/results'
      fullPath: '/dashboard/athlete/results'
      preLoaderRoute: typeof DashboardAthleteResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/athlete/reach': {
      id: '/dashboard/athlete/reach'
      path: '/dashboard/athlete/reach'
      fullPath: '/dashboard/athlete/reach'
      preLoaderRoute: typeof DashboardAthleteReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/athlete/profile': {
      id: '/dashboard/athlete/profile'
      path: '/dashboard/athlete/profile'
      fullPath: '/dashboard/athlete/profile'
      preLoaderRoute: typeof DashboardAthleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/athlete/connections': {
      id: '/dashboard/athlete/connections'
      path: '/dashboard/athlete/connections'
      fullPath: '/dashboard/athlete/connections'
      preLoaderRoute: typeof DashboardAthleteConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AthletesSlugRoute: AthletesSlugRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AthletesIndexRoute: AthletesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DashboardAthleteProfileRoute: DashboardAthleteProfileRoute,
  DashboardAthleteReachRoute: DashboardAthleteReachRoute,
  DashboardAthleteResultsRoute: DashboardAthleteResultsRoute,
  DashboardAthleteConnectionsRoute: DashboardAthleteConnectionsRoute,
  DashboardSponsorAthletesRoute: DashboardSponsorAthletesRoute,
  DashboardSponsorDiscoverRoute: DashboardSponsorDiscoverRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAthleteIndexRoute: DashboardAthleteIndexRoute,
  DashboardSponsorIndexRoute: DashboardSponsorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
